<?php

namespace ContainerHGXMaeg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._8VsPQl.App\Controller\Api\UserController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._8VsPQl.App\\Controller\\Api\\UserController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Api\\UserController::list()', $container);
    }
}
