services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${WEB_PORT}:8000" # Map Symfony's built-in server to localhost:8000
    volumes:
      - .:/app:cached # Sync project files for live updates
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/symfony"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: symfony
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Nginx on localhost:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:cached
    depends_on:
      - web

volumes:
  db-data:
