FROM php:8.2-cli

RUN apt-get update \
 && apt-get install -y unzip git curl libpq-dev libicu-dev \
 && docker-php-ext-install pdo pdo_pgsql intl \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-interaction --optimize-autoloader --no-scripts

COPY . .

CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
