<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHGXMaeg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHGXMaeg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHGXMaeg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHGXMaeg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHGXMaeg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HGXMaeg',
    'container.build_id' => 'fb6e71a8',
    'container.build_time' => 1745483636,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHGXMaeg');
